---
title: "Data Science I Homework 6"
author: "Huanyu Chen"
date: "`r Sys.Date()`"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)
library(purrr)
library(ggplot2)
library(MASS)
library(modelr)
```

# Problem 1

```{r}

```

# Problem 2
## Load Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  dplyr::select(name, id, everything())
```

## Bootstrap
```{r}
result = weather_df |>
  modelr::bootstrap(n = 500) |>
  mutate(
    weather_lm = map(strap, ~lm(tmax ~ tmin + prcp, data = .x)),
    weather_lm_r2 = map(weather_lm, broom::tidy),
    weather_lm_beta = map(weather_lm, broom::glance)
    ) |>
  unnest(weather_lm_r2, weather_lm_beta) |>
  dplyr::select(term, estimate, r.squared) |>
  pivot_wider(names_from = term, values_from = estimate) |>
  rename(
    beta_0 = `(Intercept)`,
    beta_1 = tmin,
    beta_2 = prcp) |>
  summarise(r_squared = r.squared,
            log_beta1_2 = log(beta_1*beta_2),
            log_beta0_1 = log(beta_0*beta_1))
  
head(result)
```

## Plot Distributions: r^2
```{r}
result |>
  ggplot(aes(x = r_squared)) +
  geom_histogram() +
  labs(title = "Distribution of r^2 Estimates",
       x = "r^2 estimates")
```

According to the graph, we find that the estimates for r\^2 are around 0.92, which means that `tmin` and `prcp` are good predictors of `tmax`.

## Plot Distributions: log(beta_1 * beta_2)
```{r}
result |>
  ggplot(aes(x = log_beta1_2)) +
  geom_histogram() +
  labs(title = "Distribution of log(beta_1 * beta_2) Estimates",
       x = "log(beta_1 * beta_2) estimates")
```

According to the graph, we find that the estimates for log(beta_1 \* beta_2) are left skewed, with most frequencies around -6.

## 95% Confidence Interval
```{r}
r2_ci = quantile(pull(result, r_squared),
                 probs = c(0.025,0.975))
r2_ci

log_beta01_ci = quantile(pull(result, log_beta0_1),
                         probs = c(0.025,0.975))
log_beta01_ci
```

# Problem 3

```{r}

```
